# Generated by Django 3.2.4 on 2021-09-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.FloatField()),
                ('universidad', models.FloatField()),
                ('profesion', models.FloatField()),
                ('ciudad', models.FloatField()),
                ('cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PredResults',
        ),
    ]
