# Generated by Django 3.2.4 on 2021-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_rename_results_predicciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicciones',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='cliente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='profesion',
            field=models.CharField(max_length=50),
        ),
    ]
