# Generated by Django 3.2.4 on 2021-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_auto_20211008_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicciones',
            name='ciudad',
            field=models.CharField(max_length=20, verbose_name='Ciudad de la Universidad'),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='cliente',
            field=models.CharField(max_length=10, verbose_name='Posibilidad de cliente'),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de la persona'),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='profesion',
            field=models.CharField(max_length=80, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='predicciones',
            name='universidad',
            field=models.CharField(max_length=50, verbose_name='Universidad'),
        ),
    ]
