# Generated by Django 3.2.4 on 2021-10-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda_nombres',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
