# Generated by Django 3.2.4 on 2021-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_busqueda_nombres_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda_nombres',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='busqueda_nombres',
            name='cliente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='busqueda_nombres',
            name='profesion',
            field=models.CharField(max_length=50),
        ),
    ]
