# Generated by Django 3.2.4 on 2021-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20211008_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la persona')),
                ('universidad', models.CharField(max_length=50, verbose_name='Universidad')),
                ('profesion', models.CharField(max_length=80, verbose_name='Profesion')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad de la Universidad')),
                ('cliente', models.CharField(max_length=10, verbose_name='Posibilidad de cliente')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name_plural': 'Nombres buscados',
                'get_latest_by': 'fecha',
            },
        ),
    ]
